# Generated by Django 2.1 on 2020-04-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('lifestyle', models.CharField(max_length=200, null=True)),
                ('big_cate', models.CharField(max_length=200, null=True)),
                ('sub_lifestyle', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='api.Store'),
        ),
    ]
