# Generated by Django 2.1 on 2020-04-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200426_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='api.Store')),
            ],
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='img_url',
            new_name='detail_lifestyle',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='sub_lifestyle',
            new_name='map_lifestyle',
        ),
    ]
