# Generated by Django 2.1 on 2020-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200426_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
